import { useRouter } from 'expo-router';
import { 
  Calendar, 
  ChevronLeft, 
  Download, 
  TrendingDown, 
  TrendingUp,
  Users,
  Activity
} from 'lucide-react-native';
import React, { useState, useEffect } from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  Dimensions,
  Alert,
  Share,
} from 'react-native';
import { useMedication, AdherenceReport } from '@/contexts/MedicationContext';
import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';

const { width } = Dimensions.get('window');

export default function AdherenceReportsScreen() {
  const router = useRouter();
  const { getAdherenceReport, getAdherenceHistory } = useMedication();
  
  const [selectedPeriod, setSelectedPeriod] = useState<'daily' | 'weekly' | 'monthly'>('weekly');
  const [currentDate, setCurrentDate] = useState(new Date().toISOString().split('T')[0]);
  const [report, setReport] = useState<AdherenceReport | null>(null);
  const [adherenceHistory, setAdherenceHistory] = useState<any[]>([]);

  useEffect(() => {
    loadReportData();
  }, [selectedPeriod, currentDate]);

  const loadReportData = async () => {
    const reportData = getAdherenceReport(selectedPeriod, currentDate);
    setReport(reportData);
    
    const historyDays = selectedPeriod === 'daily' ? 30 : selectedPeriod === 'weekly' ? 12 * 7 : 365;
    const history = await getAdherenceHistory(historyDays);
    setAdherenceHistory(history);
  };

  const getAdherenceColor = (percentage: number) => {
    if (percentage >= 80) return '#10B981';
    if (percentage >= 60) return '#F59E0B';
    return '#EF4444';
  };

  const getAdherenceStatus = (percentage: number) => {
    if (percentage >= 80) return 'Excellent';
    if (percentage >= 60) return 'Good';
    return 'Needs Improvement';
  };

  const generateReportContent = () => {
    if (!report) return '';
    
    const formatDate = (dateStr: string) => {
      return new Date(dateStr).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
    };
    
    const reportContent = `
ADHERENCE REPORT
================

Report Type: ${selectedPeriod.charAt(0).toUpperCase() + selectedPeriod.slice(1)}
Period: ${formatDate(report.startDate)} - ${formatDate(report.endDate)}
Generated: ${new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })}

OVERALL ADHERENCE
=================
Adherence Rate: ${report.adherencePercentage}%
Status: ${getAdherenceStatus(report.adherencePercentage)}

DETAILED STATISTICS
==================
Total Scheduled Doses: ${report.totalScheduled}
Doses Taken: ${report.taken}
Doses Missed: ${report.missed}
Doses Skipped: ${report.skipped}

PERFORMANCE INSIGHTS
===================
• Best Performance Time: Morning (8-10 AM)
• Most Missed Medication: Evening Doses
• ${selectedPeriod.charAt(0).toUpperCase() + selectedPeriod.slice(1)} Average: ${report.adherencePercentage}%
• Consistency Score: ${report.adherencePercentage >= 80 ? 'High' : report.adherencePercentage >= 60 ? 'Medium' : 'Low'}

COLOR GUIDE
===========
• Green (80%+): Good adherence
• Yellow (60-79%): Fair adherence
• Red (<60%): Poor adherence

RECOMMENDATIONS
===============
${report.adherencePercentage >= 80 
  ? '• Excellent work! Keep maintaining this level of adherence.\n• Continue with current medication routine.'
  : report.adherencePercentage >= 60
  ? '• Good progress, but there\'s room for improvement.\n• Consider setting more reminders for missed doses.\n• Review medication schedule with healthcare provider.'
  : '• Adherence needs significant improvement.\n• Consult with healthcare provider immediately.\n• Consider medication management tools or caregiver support.\n• Review barriers to taking medications as prescribed.'
}

---
This report was generated by Heath Care App
`;
    
    return reportContent;
  };

  const downloadReport = async () => {
    try {
      if (!report) {
        Alert.alert('Error', 'No report data available to download.');
        return;
      }

      const reportContent = generateReportContent();
      const fileName = `adherence-report-${selectedPeriod}-${new Date().toISOString().split('T')[0]}.txt`;
      const fileUri = FileSystem.documentDirectory + fileName;

      await FileSystem.writeAsStringAsync(fileUri, reportContent, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      // Check if sharing is available
      const isAvailable = await Sharing.isAvailableAsync();
      if (isAvailable) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'text/plain',
          dialogTitle: 'Share Adherence Report',
        });
      } else {
        // Fallback to system share
        await Share.share({
          message: reportContent,
          title: 'Adherence Report',
        });
      }

      Alert.alert(
        'Report Generated', 
        'Your adherence report has been generated and is ready to share.',
        [{ text: 'OK' }]
      );
    } catch (error) {
      console.error('Error generating report:', error);
      Alert.alert(
        'Error', 
        'Failed to generate report. Please try again.',
        [{ text: 'OK' }]
      );
    }
  };

  const PeriodSelector = () => (
    <View style={styles.periodSelector}>
      {(['daily', 'weekly', 'monthly'] as const).map((period) => (
        <TouchableOpacity
          key={period}
          style={[
            styles.periodButton,
            selectedPeriod === period && styles.periodButtonActive
          ]}
          onPress={() => setSelectedPeriod(period)}
        >
          <Text style={[
            styles.periodButtonText,
            selectedPeriod === period && styles.periodButtonTextActive
          ]}>
            {period.charAt(0).toUpperCase() + period.slice(1)}
          </Text>
        </TouchableOpacity>
      ))}
    </View>
  );

  const AdherenceOverview = () => {
    if (!report) return null;

    return (
      <View style={styles.overviewCard}>
        <View style={styles.overviewHeader}>
          <Text style={styles.overviewTitle}>Adherence Overview</Text>
          <View style={[styles.statusBadge, { backgroundColor: getAdherenceColor(report.adherencePercentage) }]}>
            <Text style={styles.statusBadgeText}>
              {getAdherenceStatus(report.adherencePercentage)}
            </Text>
          </View>
        </View>
        
        <View style={styles.adherenceCircle}>
          <Text style={styles.adherencePercentage}>{report.adherencePercentage}%</Text>
          <Text style={styles.adherenceLabel}>Adherence Rate</Text>
        </View>
        
        <View style={styles.statsGrid}>
          <View style={styles.statItem}>
            <Text style={styles.statNumber}>{report.taken}</Text>
            <Text style={styles.statLabel}>Taken</Text>
            <View style={[styles.statIndicator, { backgroundColor: '#10B981' }]} />
          </View>
          
          <View style={styles.statItem}>
            <Text style={styles.statNumber}>{report.missed}</Text>
            <Text style={styles.statLabel}>Missed</Text>
            <View style={[styles.statIndicator, { backgroundColor: '#EF4444' }]} />
          </View>
          
          <View style={styles.statItem}>
            <Text style={styles.statNumber}>{report.skipped}</Text>
            <Text style={styles.statLabel}>Skipped</Text>
            <View style={[styles.statIndicator, { backgroundColor: '#F59E0B' }]} />
          </View>
          
          <View style={styles.statItem}>
            <Text style={styles.statNumber}>{report.totalScheduled}</Text>
            <Text style={styles.statLabel}>Total</Text>
            <View style={[styles.statIndicator, { backgroundColor: '#6B7280' }]} />
          </View>
        </View>
      </View>
    );
  };

  const TrendChart = () => {
    const recentHistory = adherenceHistory && adherenceHistory.length > 0 ? adherenceHistory.slice(-14) : []; // Last 14 days
    const trend = recentHistory.length > 1 ? 
      recentHistory[recentHistory.length - 1].percentage - recentHistory[0].percentage : 0;

    return (
      <View style={styles.trendCard}>
        <View style={styles.trendHeader}>
          <Text style={styles.trendTitle}>14-Day Trend</Text>
          <View style={styles.trendIndicator}>
            {trend > 0 ? (
              <TrendingUp size={16} color="#10B981" />
            ) : (
              <TrendingDown size={16} color="#EF4444" />
            )}
            <Text style={[
              styles.trendText,
              { color: trend > 0 ? '#10B981' : '#EF4444' }
            ]}>
              {Math.abs(trend).toFixed(1)}%
            </Text>
          </View>
        </View>
        
        <View style={styles.miniChart}>
          {recentHistory.length > 0 ? recentHistory.map((day, index) => (
            <View key={index} style={styles.miniBar}>
              <View 
                style={[
                  styles.miniBarFill,
                  { 
                    height: `${day.percentage}%`,
                    backgroundColor: getAdherenceColor(day.percentage)
                  }
                ]}
              />
            </View>
          )) : (
            <Text style={{ fontSize: 14, color: '#6B7280', textAlign: 'center' }}>No trend data available</Text>
          )}
        </View>
      </View>
    );
  };

  const CaregiverInsights = () => (
    <View style={styles.insightsCard}>
      <View style={styles.insightsHeader}>
        <Users size={20} color="#1E3A8A" />
        <Text style={styles.insightsTitle}>Caregiver Insights</Text>
      </View>
      
      <View style={styles.insightsList}>
        <View style={styles.insightItem}>
          <Text style={styles.insightLabel}>Best Performance Time</Text>
          <Text style={styles.insightValue}>Morning (8-10 AM)</Text>
        </View>
        
        <View style={styles.insightItem}>
          <Text style={styles.insightLabel}>Most Missed Medication</Text>
          <Text style={styles.insightValue}>Evening Doses</Text>
        </View>
        
        <View style={styles.insightItem}>
          <Text style={styles.insightLabel}>Weekly Average</Text>
          <Text style={styles.insightValue}>{report?.adherencePercentage || 0}%</Text>
        </View>
        
        <View style={styles.insightItem}>
          <Text style={styles.insightLabel}>Consistency Score</Text>
          <Text style={styles.insightValue}>
            {report && report.adherencePercentage >= 80 ? 'High' : 
             report && report.adherencePercentage >= 60 ? 'Medium' : 'Low'}
          </Text>
        </View>
      </View>
    </View>
  );

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#FFFFFF" />
      
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity 
          style={styles.backButton}
          onPress={() => router.back()}
        >
          <ChevronLeft size={24} color="#1F2937" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Adherence Reports</Text>
        <TouchableOpacity style={styles.downloadButton} onPress={downloadReport}>
          <Download size={20} color="#1E3A8A" />
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {/* Period Selector */}
        <View style={styles.section}>
          <PeriodSelector />
        </View>

        {/* Adherence Overview */}
        <View style={styles.section}>
          <AdherenceOverview />
        </View>

        {/* Trend Chart */}
        <View style={styles.section}>
          <TrendChart />
        </View>

        {/* Caregiver Insights */}
        <View style={styles.section}>
          <CaregiverInsights />
        </View>

        {/* Color Legend */}
        <View style={styles.section}>
          <View style={styles.legendCard}>
            <Text style={styles.legendTitle}>Color Guide</Text>
            <View style={styles.legendItems}>
              <View style={styles.legendItem}>
                <View style={[styles.legendColor, { backgroundColor: '#10B981' }]} />
                <Text style={styles.legendText}>Good (80%+)</Text>
              </View>
              <View style={styles.legendItem}>
                <View style={[styles.legendColor, { backgroundColor: '#F59E0B' }]} />
                <Text style={styles.legendText}>Fair (60-79%)</Text>
              </View>
              <View style={styles.legendItem}>
                <View style={[styles.legendColor, { backgroundColor: '#EF4444' }]} />
                <Text style={styles.legendText}>Poor (&lt;60%)</Text>
              </View>
            </View>
          </View>
        </View>

        <View style={styles.bottomSpacer} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
  },
  downloadButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E0E7FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  section: {
    marginTop: 24,
  },
  periodSelector: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 4,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  periodButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  periodButtonActive: {
    backgroundColor: '#1E3A8A',
  },
  periodButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  periodButtonTextActive: {
    color: '#FFFFFF',
  },
  overviewCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  overviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  overviewTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  statusBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  adherenceCircle: {
    alignItems: 'center',
    marginBottom: 24,
  },
  adherencePercentage: {
    fontSize: 48,
    fontWeight: '800',
    color: '#1F2937',
  },
  adherenceLabel: {
    fontSize: 16,
    color: '#6B7280',
    marginTop: 4,
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statItem: {
    alignItems: 'center',
    flex: 1,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
  },
  statIndicator: {
    width: 24,
    height: 4,
    borderRadius: 2,
  },
  trendCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  trendHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  trendTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
  },
  trendIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  trendText: {
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 4,
  },
  miniChart: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: 60,
  },
  miniBar: {
    width: 12,
    height: 60,
    backgroundColor: '#F1F5F9',
    borderRadius: 2,
    justifyContent: 'flex-end',
  },
  miniBarFill: {
    width: '100%',
    borderRadius: 2,
    minHeight: 2,
  },
  insightsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  insightsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  insightsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginLeft: 8,
  },
  insightsList: {
    gap: 12,
  },
  insightItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  insightLabel: {
    fontSize: 14,
    color: '#6B7280',
  },
  insightValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
  },
  legendCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  legendTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 16,
  },
  legendItems: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  legendItem: {
    alignItems: 'center',
  },
  legendColor: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginBottom: 8,
  },
  legendText: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
  },
  bottomSpacer: {
    height: 40,
  },
});
