import { useRouter } from 'expo-router';
import { 
  Calendar, 
  CheckCircle, 
  Clock, 
  Pill, 
  TrendingUp, 
  X, 
  XCircle,
  BarChart3,
  FileText,
  Share,
  Download
} from 'lucide-react-native';
import React, { useEffect, useState } from 'react';
import {
  SafeAreaView,
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
  Alert,
  Share as RNShare,
} from 'react-native';
import { useMedication, EnrichedMedicationSchedule } from '@/contexts/MedicationContext';

export default function MedicationTrackerScreen() {
  const router = useRouter();
  const { 
    getTodaysIntakes, 
    updateIntakeStatus, 
    getAdherenceReport, 
    getAdherenceHistory,
    loadTodaysSchedule 
  } = useMedication();
  
  const [todaysIntakes, setTodaysIntakes] = useState<EnrichedMedicationSchedule[]>([]);
  const [adherenceHistory, setAdherenceHistory] = useState<any[]>([]);

  useEffect(() => {
    const initializeData = async () => {
      await loadTodaysSchedule();
      await loadTodaysData();
    };
    initializeData();
  }, []);

  const loadTodaysData = async () => {
    const intakes = getTodaysIntakes();
    setTodaysIntakes(intakes);
    
    const history = await getAdherenceHistory(7);
    setAdherenceHistory(history);
  };

  const handleIntakeAction = async (scheduleId: number, status: 'taken' | 'missed' | 'skipped') => {
    await updateIntakeStatus(scheduleId, status);
    await loadTodaysData();
    const statusText = status === 'taken' ? 'taken' : status === 'missed' ? 'marked as missed' : 'skipped';
    Alert.alert('Updated', `Medication ${statusText} successfully!`);
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'taken': return '#10B981';
      case 'missed': return '#EF4444';
      case 'skipped': return '#F59E0B';
      case 'pending': return '#6B7280';
      default: return '#6B7280';
    }
  };

  const getAdherenceColor = (percentage: number) => {
    if (percentage >= 80) return '#10B981';
    if (percentage >= 60) return '#F59E0B';
    return '#EF4444';
  };

  const generateReport = async () => {
    const today = new Date().toISOString().split('T')[0];
    const dailyReport = getAdherenceReport('daily', today);
    const weeklyReport = getAdherenceReport('weekly', today);
    const monthlyReport = getAdherenceReport('monthly', today);
    
    const reportContent = `📋 MEDICATION ADHERENCE REPORT
Generated: ${new Date().toLocaleDateString()}

📊 DAILY REPORT
• Adherence: ${dailyReport.adherencePercentage}%
• Taken: ${dailyReport.taken}/${dailyReport.totalScheduled}
• Missed: ${dailyReport.missed}
• Skipped: ${dailyReport.skipped}

📈 WEEKLY REPORT  
• Adherence: ${weeklyReport.adherencePercentage}%
• Total Scheduled: ${weeklyReport.totalScheduled}
• Successfully Taken: ${weeklyReport.taken}

📅 MONTHLY OVERVIEW
• Overall Adherence: ${monthlyReport.adherencePercentage}%
• Total Doses: ${monthlyReport.totalScheduled}
• Compliance Rate: ${monthlyReport.taken}/${monthlyReport.totalScheduled}

💡 RECOMMENDATIONS
${monthlyReport.adherencePercentage >= 80 ? '✅ Excellent adherence! Keep up the great work.' : 
  monthlyReport.adherencePercentage >= 60 ? '⚠️ Good adherence. Consider setting more reminders.' : 
  '🚨 Adherence needs improvement. Please consult your healthcare provider.'}

Generated by AppCore Health Tracker`;

    RNShare.share({
      message: reportContent,
    });
  };

  const todayReport = getAdherenceReport('daily', new Date().toISOString().split('T')[0]);
  const weeklyReport = getAdherenceReport('weekly', new Date().toISOString().split('T')[0]);

  const IntakeCard = ({ intake }: { intake: EnrichedMedicationSchedule }) => (
    <View style={styles.intakeCard}>
      <View style={styles.intakeHeader}>
        <View style={styles.medicationInfo}>
          <View style={[styles.statusDot, { backgroundColor: getStatusColor(intake.status) }]} />
          <View>
            <Text style={styles.medicationName}>{intake.medicationName}</Text>
            <Text style={styles.scheduledTime}>{intake.dosage}</Text>
            <Text style={styles.scheduledTime}>
              <Clock size={12} color="#6B7280" /> {intake.time}
            </Text>
          </View>
        </View>
        <Text style={[styles.statusText, { color: getStatusColor(intake.status) }]}>
          {intake.status.toUpperCase()}
        </Text>
      </View>
      
      {intake.status === 'pending' && (
        <View style={styles.actionButtons}>
          <TouchableOpacity
            style={[styles.actionButton, styles.takenButton]}
            onPress={() => handleIntakeAction(intake.id, 'taken')}
          >
            <CheckCircle size={16} color="#FFFFFF" />
            <Text style={styles.actionButtonText}>Taken</Text>
          </TouchableOpacity>
          
          <TouchableOpacity
            style={[styles.actionButton, styles.missedButton]}
            onPress={() => handleIntakeAction(intake.id, 'missed')}
          >
            <XCircle size={16} color="#FFFFFF" />
            <Text style={styles.actionButtonText}>Missed</Text>
          </TouchableOpacity>
          
          <TouchableOpacity
            style={[styles.actionButton, styles.skippedButton]}
            onPress={() => handleIntakeAction(intake.id, 'skipped')}
          >
            <X size={16} color="#FFFFFF" />
            <Text style={styles.actionButtonText}>Skip</Text>
          </TouchableOpacity>
        </View>
      )}
    </View>
  );

  const AdherenceChart = () => (
    <View style={styles.chartContainer}>
      <Text style={styles.chartTitle}>7-Day Adherence History</Text>
      <View style={styles.chartBars}>
        {adherenceHistory && adherenceHistory.length > 0 ? adherenceHistory.map((day, index) => (
          <View key={index} style={styles.chartBar}>
            <View 
              style={[
                styles.bar, 
                { 
                  height: Math.max(day.percentage, 5), 
                  backgroundColor: getAdherenceColor(day.percentage) 
                }
              ]} 
            />
            <Text style={styles.barLabel}>
              {new Date(day.date).toLocaleDateString('en', { weekday: 'short' })}
            </Text>
            <Text style={styles.barPercentage}>{day.percentage}%</Text>
          </View>
        )) : (
          <Text style={styles.emptyStateText}>No adherence data available</Text>
        )}
      </View>
    </View>
  );

  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" backgroundColor="#FFFFFF" />
      
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Medication Tracker</Text>
        <View style={styles.headerActionButtons}>
          <TouchableOpacity 
            style={styles.reportsButton}
            onPress={() => router.push('/(tabs)/adherence-reports')}
          >
            <BarChart3 size={20} color="#3B82F6" />
            <Text style={styles.reportsButtonText}>View Reports</Text>
          </TouchableOpacity>
          
          <TouchableOpacity 
            style={styles.generateButton}
            onPress={generateReport}
          >
            <FileText size={20} color="#FFFFFF" />
            <Text style={styles.generateButtonText}>Generate Report</Text>
          </TouchableOpacity>
        </View>
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {/* Today's Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Today's Progress</Text>
          <View style={styles.summaryCards}>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryNumber}>{todayReport.taken}</Text>
              <Text style={styles.summaryLabel}>Taken</Text>
              <View style={[styles.summaryIndicator, { backgroundColor: '#10B981' }]} />
            </View>
            
            <View style={styles.summaryCard}>
              <Text style={styles.summaryNumber}>{todayReport.missed}</Text>
              <Text style={styles.summaryLabel}>Missed</Text>
              <View style={[styles.summaryIndicator, { backgroundColor: '#EF4444' }]} />
            </View>
            
            <View style={styles.summaryCard}>
              <Text style={styles.summaryNumber}>{todayReport.adherencePercentage}%</Text>
              <Text style={styles.summaryLabel}>Adherence</Text>
              <View style={[styles.summaryIndicator, { backgroundColor: getAdherenceColor(todayReport.adherencePercentage) }]} />
            </View>
          </View>
        </View>

        {/* Weekly Overview */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Weekly Overview</Text>
          <View style={styles.weeklyCard}>
            <View style={styles.weeklyStats}>
              <View style={styles.weeklyStat}>
                <Text style={styles.weeklyNumber}>{weeklyReport.adherencePercentage}%</Text>
                <Text style={styles.weeklyLabel}>Weekly Adherence</Text>
              </View>
              <View style={styles.weeklyStat}>
                <Text style={styles.weeklyNumber}>{weeklyReport.taken}/{weeklyReport.totalScheduled}</Text>
                <Text style={styles.weeklyLabel}>Doses Taken</Text>
              </View>
            </View>
            <View style={[styles.adherenceBar, { backgroundColor: getAdherenceColor(weeklyReport.adherencePercentage) }]}>
              <View 
                style={[
                  styles.adherenceProgress, 
                  { width: `${weeklyReport.adherencePercentage}%` }
                ]} 
              />
            </View>
          </View>
        </View>

        {/* Adherence Chart */}
        <View style={styles.section}>
          <AdherenceChart />
        </View>


        <View style={styles.bottomSpacer} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  headerActionButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  reportsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  reportsButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3B82F6',
  },
  generateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#3B82F6',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    gap: 6,
  },
  generateButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1F2937',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  section: {
    marginTop: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 16,
  },
  summaryCards: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 4,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  summaryNumber: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1F2937',
    marginBottom: 4,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
  },
  summaryIndicator: {
    width: 24,
    height: 4,
    borderRadius: 2,
  },
  weeklyCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  weeklyStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  weeklyStat: {
    alignItems: 'center',
  },
  weeklyNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 4,
  },
  weeklyLabel: {
    fontSize: 14,
    color: '#6B7280',
  },
  adherenceBar: {
    height: 8,
    backgroundColor: '#F1F5F9',
    borderRadius: 4,
    overflow: 'hidden',
  },
  adherenceProgress: {
    height: '100%',
    borderRadius: 4,
  },
  chartContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  chartTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 16,
    textAlign: 'center',
  },
  chartBars: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: 120,
  },
  chartBar: {
    alignItems: 'center',
    flex: 1,
  },
  bar: {
    width: 20,
    borderRadius: 4,
    marginBottom: 8,
  },
  barLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 2,
  },
  barPercentage: {
    fontSize: 10,
    color: '#9CA3AF',
  },
  intakeCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  intakeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  medicationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  statusDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 12,
  },
  medicationName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 2,
  },
  scheduledTime: {
    fontSize: 14,
    color: '#6B7280',
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    marginHorizontal: 4,
  },
  takenButton: {
    backgroundColor: '#10B981',
  },
  missedButton: {
    backgroundColor: '#EF4444',
  },
  skippedButton: {
    backgroundColor: '#F59E0B',
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 4,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyStateText: {
    fontSize: 16,
    color: '#6B7280',
    marginTop: 12,
  },
  bottomSpacer: {
    height: 40,
  },
});
