/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/screen2` | `/screen2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/screen3` | `/screen3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-medicine` | `/add-medicine`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/app-settings` | `/app-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/edit-medicine` | `/edit-medicine`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/privacy-security` | `/privacy-security`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reminder-settings` | `/reminder-settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/screen2` | `/screen2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/screen3` | `/screen3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/add-medicine` | `/add-medicine`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/app-settings` | `/app-settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/edit-medicine` | `/edit-medicine`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/privacy-security` | `/privacy-security`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/reminder-settings` | `/reminder-settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/screen2${`?${string}` | `#${string}` | ''}` | `/screen2${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/screen3${`?${string}` | `#${string}` | ''}` | `/screen3${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/add-medicine${`?${string}` | `#${string}` | ''}` | `/add-medicine${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/app-settings${`?${string}` | `#${string}` | ''}` | `/app-settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/edit-medicine${`?${string}` | `#${string}` | ''}` | `/edit-medicine${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/privacy-security${`?${string}` | `#${string}` | ''}` | `/privacy-security${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/reminder-settings${`?${string}` | `#${string}` | ''}` | `/reminder-settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/screen2` | `/screen2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/screen3` | `/screen3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-medicine` | `/add-medicine`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/app-settings` | `/app-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/edit-medicine` | `/edit-medicine`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/privacy-security` | `/privacy-security`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/reminder-settings` | `/reminder-settings`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
